//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ContractWordClient {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl1;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl6;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl7;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl8;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl9;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl10;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl11;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl12;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl13;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl14;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl15;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl16;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl17;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl datePickerContentControl1;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl datePickerContentControl2;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl18;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl19;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        internal System.Windows.Forms.BindingSource displayContractBindingSource;
        
        private System.ComponentModel.IContainer components;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn idDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn address1DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn address2DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn address3DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn address4DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn address5DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn tenant1DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn tenant2DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn dateFromDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn dateToDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordIdDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn rentDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn depositDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn mobileDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn emailDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordNameDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordAddress1DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordAddress2DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordAddress3DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordAddress4DataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn landlordAddress5DataGridViewTextBoxColumn;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
            this.plainTextContentControl1.DataBindings.Add("Text", this.displayContractBindingSource, "LandlordName", true, this.plainTextContentControl1.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl6.DataBindings.Add("Text", this.displayContractBindingSource, "Tenant1", true, this.plainTextContentControl6.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl7.DataBindings.Add("Text", this.displayContractBindingSource, "Tenant2", true, this.plainTextContentControl7.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl8.DataBindings.Add("Text", this.displayContractBindingSource, "Address1", true, this.plainTextContentControl8.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl9.DataBindings.Add("Text", this.displayContractBindingSource, "Address2", true, this.plainTextContentControl9.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl10.DataBindings.Add("Text", this.displayContractBindingSource, "Address3", true, this.plainTextContentControl10.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl11.DataBindings.Add("Text", this.displayContractBindingSource, "Address4", true, this.plainTextContentControl11.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl12.DataBindings.Add("Text", this.displayContractBindingSource, "Address5", true, this.plainTextContentControl12.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl13.DataBindings.Add("Text", this.displayContractBindingSource, "LandlordAddress2", true, this.plainTextContentControl13.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl14.DataBindings.Add("Text", this.displayContractBindingSource, "LandlordAddress1", true, this.plainTextContentControl14.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl15.DataBindings.Add("Text", this.displayContractBindingSource, "LandlordAddress3", true, this.plainTextContentControl15.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl16.DataBindings.Add("Text", this.displayContractBindingSource, "LandlordAddress4", true, this.plainTextContentControl16.DataBindings.DefaultDataSourceUpdateMode);
            this.plainTextContentControl17.DataBindings.Add("Text", this.displayContractBindingSource, "LandlordAddress5", true, this.plainTextContentControl17.DataBindings.DefaultDataSourceUpdateMode);
            this.datePickerContentControl1.DataBindings.Add("Text", this.displayContractBindingSource, "DateFrom", true, System.Windows.Forms.DataSourceUpdateMode.Never, null, "d");
            this.datePickerContentControl2.DataBindings.Add("Text", this.displayContractBindingSource, "DateTo", true, System.Windows.Forms.DataSourceUpdateMode.Never, null, "d");
            this.plainTextContentControl18.DataBindings.Add("Text", this.displayContractBindingSource, "Rent", true, System.Windows.Forms.DataSourceUpdateMode.Never, null, "C2");
            this.plainTextContentControl19.DataBindings.Add("Text", this.displayContractBindingSource, "Deposit", true, System.Windows.Forms.DataSourceUpdateMode.Never, null, "C2");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.plainTextContentControl1.BeginInit();
            this.plainTextContentControl6.BeginInit();
            this.plainTextContentControl7.BeginInit();
            this.plainTextContentControl8.BeginInit();
            this.plainTextContentControl9.BeginInit();
            this.plainTextContentControl10.BeginInit();
            this.plainTextContentControl11.BeginInit();
            this.plainTextContentControl12.BeginInit();
            this.plainTextContentControl13.BeginInit();
            this.plainTextContentControl14.BeginInit();
            this.plainTextContentControl15.BeginInit();
            this.plainTextContentControl16.BeginInit();
            this.plainTextContentControl17.BeginInit();
            this.datePickerContentControl1.BeginInit();
            this.datePickerContentControl2.BeginInit();
            this.plainTextContentControl18.BeginInit();
            this.plainTextContentControl19.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.plainTextContentControl19.EndInit();
            this.plainTextContentControl18.EndInit();
            this.datePickerContentControl2.EndInit();
            this.datePickerContentControl1.EndInit();
            this.plainTextContentControl17.EndInit();
            this.plainTextContentControl16.EndInit();
            this.plainTextContentControl15.EndInit();
            this.plainTextContentControl14.EndInit();
            this.plainTextContentControl13.EndInit();
            this.plainTextContentControl12.EndInit();
            this.plainTextContentControl11.EndInit();
            this.plainTextContentControl10.EndInit();
            this.plainTextContentControl9.EndInit();
            this.plainTextContentControl8.EndInit();
            this.plainTextContentControl7.EndInit();
            this.plainTextContentControl6.EndInit();
            this.plainTextContentControl1.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.plainTextContentControl1 = Globals.Factory.CreatePlainTextContentControl(null, null, "1405109704", "plainTextContentControl1", this);
            this.plainTextContentControl6 = Globals.Factory.CreatePlainTextContentControl(null, null, "621744094", "plainTextContentControl6", this);
            this.plainTextContentControl7 = Globals.Factory.CreatePlainTextContentControl(null, null, "3945095966", "plainTextContentControl7", this);
            this.plainTextContentControl8 = Globals.Factory.CreatePlainTextContentControl(null, null, "3468988985", "plainTextContentControl8", this);
            this.plainTextContentControl9 = Globals.Factory.CreatePlainTextContentControl(null, null, "947351609", "plainTextContentControl9", this);
            this.plainTextContentControl10 = Globals.Factory.CreatePlainTextContentControl(null, null, "4235334694", "plainTextContentControl10", this);
            this.plainTextContentControl11 = Globals.Factory.CreatePlainTextContentControl(null, null, "2958202021", "plainTextContentControl11", this);
            this.plainTextContentControl12 = Globals.Factory.CreatePlainTextContentControl(null, null, "1021131526", "plainTextContentControl12", this);
            this.plainTextContentControl13 = Globals.Factory.CreatePlainTextContentControl(null, null, "1077477216", "plainTextContentControl13", this);
            this.plainTextContentControl14 = Globals.Factory.CreatePlainTextContentControl(null, null, "627741218", "plainTextContentControl14", this);
            this.plainTextContentControl15 = Globals.Factory.CreatePlainTextContentControl(null, null, "331421264", "plainTextContentControl15", this);
            this.plainTextContentControl16 = Globals.Factory.CreatePlainTextContentControl(null, null, "2569832018", "plainTextContentControl16", this);
            this.plainTextContentControl17 = Globals.Factory.CreatePlainTextContentControl(null, null, "3281669492", "plainTextContentControl17", this);
            this.datePickerContentControl1 = Globals.Factory.CreateDatePickerContentControl(null, null, "2565749136", "datePickerContentControl1", this);
            this.datePickerContentControl2 = Globals.Factory.CreateDatePickerContentControl(null, null, "4189851039", "datePickerContentControl2", this);
            this.plainTextContentControl18 = Globals.Factory.CreatePlainTextContentControl(null, null, "1487290627", "plainTextContentControl18", this);
            this.plainTextContentControl19 = Globals.Factory.CreatePlainTextContentControl(null, null, "3939851804", "plainTextContentControl19", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            this.components = new System.ComponentModel.Container();
            this.displayContractBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.idDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.address1DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.address2DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.address3DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.address4DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.address5DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tenant1DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tenant2DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dateFromDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dateToDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordIdDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.rentDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.depositDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.mobileDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.emailDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordNameDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordAddress1DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordAddress2DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordAddress3DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordAddress4DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.landlordAddress5DataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            ((System.ComponentModel.ISupportInitialize)(this.displayContractBindingSource)).BeginInit();
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // plainTextContentControl1
            // 
            this.plainTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // displayContractBindingSource
            // 
            this.displayContractBindingSource.DataSource = typeof(LettingApiLib.Models.DisplayContract);
            // 
            // idDataGridViewTextBoxColumn
            // 
            this.idDataGridViewTextBoxColumn.DataPropertyName = "Id";
            this.idDataGridViewTextBoxColumn.HeaderText = "Id";
            this.idDataGridViewTextBoxColumn.Name = "idDataGridViewTextBoxColumn";
            // 
            // address1DataGridViewTextBoxColumn
            // 
            this.address1DataGridViewTextBoxColumn.DataPropertyName = "Address1";
            this.address1DataGridViewTextBoxColumn.HeaderText = "Address1";
            this.address1DataGridViewTextBoxColumn.Name = "address1DataGridViewTextBoxColumn";
            // 
            // address2DataGridViewTextBoxColumn
            // 
            this.address2DataGridViewTextBoxColumn.DataPropertyName = "Address2";
            this.address2DataGridViewTextBoxColumn.HeaderText = "Address2";
            this.address2DataGridViewTextBoxColumn.Name = "address2DataGridViewTextBoxColumn";
            // 
            // address3DataGridViewTextBoxColumn
            // 
            this.address3DataGridViewTextBoxColumn.DataPropertyName = "Address3";
            this.address3DataGridViewTextBoxColumn.HeaderText = "Address3";
            this.address3DataGridViewTextBoxColumn.Name = "address3DataGridViewTextBoxColumn";
            // 
            // address4DataGridViewTextBoxColumn
            // 
            this.address4DataGridViewTextBoxColumn.DataPropertyName = "Address4";
            this.address4DataGridViewTextBoxColumn.HeaderText = "Address4";
            this.address4DataGridViewTextBoxColumn.Name = "address4DataGridViewTextBoxColumn";
            // 
            // address5DataGridViewTextBoxColumn
            // 
            this.address5DataGridViewTextBoxColumn.DataPropertyName = "Address5";
            this.address5DataGridViewTextBoxColumn.HeaderText = "Address5";
            this.address5DataGridViewTextBoxColumn.Name = "address5DataGridViewTextBoxColumn";
            // 
            // tenant1DataGridViewTextBoxColumn
            // 
            this.tenant1DataGridViewTextBoxColumn.DataPropertyName = "Tenant1";
            this.tenant1DataGridViewTextBoxColumn.HeaderText = "Tenant1";
            this.tenant1DataGridViewTextBoxColumn.Name = "tenant1DataGridViewTextBoxColumn";
            // 
            // tenant2DataGridViewTextBoxColumn
            // 
            this.tenant2DataGridViewTextBoxColumn.DataPropertyName = "Tenant2";
            this.tenant2DataGridViewTextBoxColumn.HeaderText = "Tenant2";
            this.tenant2DataGridViewTextBoxColumn.Name = "tenant2DataGridViewTextBoxColumn";
            // 
            // dateFromDataGridViewTextBoxColumn
            // 
            this.dateFromDataGridViewTextBoxColumn.DataPropertyName = "DateFrom";
            this.dateFromDataGridViewTextBoxColumn.HeaderText = "DateFrom";
            this.dateFromDataGridViewTextBoxColumn.Name = "dateFromDataGridViewTextBoxColumn";
            // 
            // dateToDataGridViewTextBoxColumn
            // 
            this.dateToDataGridViewTextBoxColumn.DataPropertyName = "DateTo";
            this.dateToDataGridViewTextBoxColumn.HeaderText = "DateTo";
            this.dateToDataGridViewTextBoxColumn.Name = "dateToDataGridViewTextBoxColumn";
            // 
            // landlordIdDataGridViewTextBoxColumn
            // 
            this.landlordIdDataGridViewTextBoxColumn.DataPropertyName = "LandlordId";
            this.landlordIdDataGridViewTextBoxColumn.HeaderText = "LandlordId";
            this.landlordIdDataGridViewTextBoxColumn.Name = "landlordIdDataGridViewTextBoxColumn";
            // 
            // rentDataGridViewTextBoxColumn
            // 
            this.rentDataGridViewTextBoxColumn.DataPropertyName = "Rent";
            this.rentDataGridViewTextBoxColumn.HeaderText = "Rent";
            this.rentDataGridViewTextBoxColumn.Name = "rentDataGridViewTextBoxColumn";
            // 
            // depositDataGridViewTextBoxColumn
            // 
            this.depositDataGridViewTextBoxColumn.DataPropertyName = "Deposit";
            this.depositDataGridViewTextBoxColumn.HeaderText = "Deposit";
            this.depositDataGridViewTextBoxColumn.Name = "depositDataGridViewTextBoxColumn";
            // 
            // mobileDataGridViewTextBoxColumn
            // 
            this.mobileDataGridViewTextBoxColumn.DataPropertyName = "Mobile";
            this.mobileDataGridViewTextBoxColumn.HeaderText = "Mobile";
            this.mobileDataGridViewTextBoxColumn.Name = "mobileDataGridViewTextBoxColumn";
            // 
            // emailDataGridViewTextBoxColumn
            // 
            this.emailDataGridViewTextBoxColumn.DataPropertyName = "Email";
            this.emailDataGridViewTextBoxColumn.HeaderText = "Email";
            this.emailDataGridViewTextBoxColumn.Name = "emailDataGridViewTextBoxColumn";
            // 
            // landlordNameDataGridViewTextBoxColumn
            // 
            this.landlordNameDataGridViewTextBoxColumn.DataPropertyName = "LandlordName";
            this.landlordNameDataGridViewTextBoxColumn.HeaderText = "LandlordName";
            this.landlordNameDataGridViewTextBoxColumn.Name = "landlordNameDataGridViewTextBoxColumn";
            // 
            // landlordAddress1DataGridViewTextBoxColumn
            // 
            this.landlordAddress1DataGridViewTextBoxColumn.DataPropertyName = "LandlordAddress1";
            this.landlordAddress1DataGridViewTextBoxColumn.HeaderText = "LandlordAddress1";
            this.landlordAddress1DataGridViewTextBoxColumn.Name = "landlordAddress1DataGridViewTextBoxColumn";
            // 
            // landlordAddress2DataGridViewTextBoxColumn
            // 
            this.landlordAddress2DataGridViewTextBoxColumn.DataPropertyName = "LandlordAddress2";
            this.landlordAddress2DataGridViewTextBoxColumn.HeaderText = "LandlordAddress2";
            this.landlordAddress2DataGridViewTextBoxColumn.Name = "landlordAddress2DataGridViewTextBoxColumn";
            // 
            // landlordAddress3DataGridViewTextBoxColumn
            // 
            this.landlordAddress3DataGridViewTextBoxColumn.DataPropertyName = "LandlordAddress3";
            this.landlordAddress3DataGridViewTextBoxColumn.HeaderText = "LandlordAddress3";
            this.landlordAddress3DataGridViewTextBoxColumn.Name = "landlordAddress3DataGridViewTextBoxColumn";
            // 
            // landlordAddress4DataGridViewTextBoxColumn
            // 
            this.landlordAddress4DataGridViewTextBoxColumn.DataPropertyName = "LandlordAddress4";
            this.landlordAddress4DataGridViewTextBoxColumn.HeaderText = "LandlordAddress4";
            this.landlordAddress4DataGridViewTextBoxColumn.Name = "landlordAddress4DataGridViewTextBoxColumn";
            // 
            // landlordAddress5DataGridViewTextBoxColumn
            // 
            this.landlordAddress5DataGridViewTextBoxColumn.DataPropertyName = "LandlordAddress5";
            this.landlordAddress5DataGridViewTextBoxColumn.HeaderText = "LandlordAddress5";
            this.landlordAddress5DataGridViewTextBoxColumn.Name = "landlordAddress5DataGridViewTextBoxColumn";
            // 
            // plainTextContentControl6
            // 
            this.plainTextContentControl6.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl7
            // 
            this.plainTextContentControl7.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl8
            // 
            this.plainTextContentControl8.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl9
            // 
            this.plainTextContentControl9.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl10
            // 
            this.plainTextContentControl10.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl11
            // 
            this.plainTextContentControl11.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl12
            // 
            this.plainTextContentControl12.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl13
            // 
            this.plainTextContentControl13.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl14
            // 
            this.plainTextContentControl14.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl15
            // 
            this.plainTextContentControl15.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl16
            // 
            this.plainTextContentControl16.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl17
            // 
            this.plainTextContentControl17.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // datePickerContentControl1
            // 
            this.datePickerContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // datePickerContentControl2
            // 
            this.datePickerContentControl2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl18
            // 
            this.plainTextContentControl18.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // plainTextContentControl19
            // 
            this.plainTextContentControl19.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
            ((System.ComponentModel.ISupportInitialize)(this.displayContractBindingSource)).EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.plainTextContentControl19.Dispose();
            this.plainTextContentControl18.Dispose();
            this.datePickerContentControl2.Dispose();
            this.datePickerContentControl1.Dispose();
            this.plainTextContentControl17.Dispose();
            this.plainTextContentControl16.Dispose();
            this.plainTextContentControl15.Dispose();
            this.plainTextContentControl14.Dispose();
            this.plainTextContentControl13.Dispose();
            this.plainTextContentControl12.Dispose();
            this.plainTextContentControl11.Dispose();
            this.plainTextContentControl10.Dispose();
            this.plainTextContentControl9.Dispose();
            this.plainTextContentControl8.Dispose();
            this.plainTextContentControl7.Dispose();
            this.plainTextContentControl6.Dispose();
            this.plainTextContentControl1.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
